baseURL = "https://martindomke.net"
title   = "Martin Domke"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "nord"

paginate  = 10
rssLimit  = 10
copyright = "<a href='https://creativecommons.org/licenses/by-nc/4.0/'>CC BY-NC 4.0</a>"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
disableRSS      = false
disableSitemap  = false
disable404      = false

[author]
name = "Martin Domke"

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

description  = "Martin Domke's personal site"
homeSubtitle = "Tech Lead at Qwist"
keywords = ""

disableReadOtherPosts = false
enableThemeToggle = true
enableSharingButtons = true
enableGlobalLanguageMenu = false

customCSS = []
customJS  = []

justifyContent = true

[params.footer]
trademark = 2023
rss = true
copyright = true
author = true
topText = []

[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[params.logo]
logoMark     = "$"
logoText     = "go build "
logoHomeLink = "/"
logoCursorDisabled = false
# logoCursorColor    = "#67a2c9"
logoCursorAnimate  = "2s"
logoCursorPathname = true

[params.portrait]
path     = "images/portrait.png"
alt      = "Portrait"
maxWidth = "270px"

[[params.social]]
name = "email"
url  = "mailto:gaze_adagios0b@icloud.com"

[[params.social]]
name = "github"
url  = "https://github.com/mdomke"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/martin-domke/"

[[params.social]]
name = "stackoverflow"
url  = "https://stackoverflow.com/users/3928751/mdomke"

[[params.social]]
name = "gpg"
url  = "/mdomke.asc"
